### ISSUE TITLE
Doesn't build with cxx compiler v.7.3.0

### ISSUE THREAD

**Issue by xabxx** [aws-robotics/utils-common#20]
Check out https://travis-ci.com/xabxx/utils-common/builds/101353624 for travis ci build details.

The lastest commit on release-v1 doesn't build in ROS1 melodic, and all ROS2 distros.
I checked the dockerfiles for these distros, and realized that their base are from `ubuntu:bionic`, and the c/cxx compiler version is `7.3.0`. 

I don't think we should downgrade the compiler version in these docker containers just to pass the build. I think we should fix the commit that uses `std:ceil`.

I made the PR that uses `std:ceil`, please pull me in when starting to investigate to get context of what I was trying to fix.

**Comment by AAlon** [comment]
This has already been fixed in master by adding `#include <cmath>`
https://github.com/aws-robotics/utils-common/blob/32f622c6aa7f61b13b5e6873bc64d5ef687e0809/aws_common/test/sdk_utils/throttling_manager_test.cpp#L21
Build succeeds:
https://travis-ci.org/AAlon/ROS1Prerelease/jobs/495071957

**Comment by juanrh** [comment]
Closing as won't fix as this was already fixed on master
