### ISSUE TITLE
Release aws_common (aka utils-common) into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [aws-robotics/utils-common#55]
Would you mind releasing `aws_common` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 11 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by raghaprasad** [comment]
@sloretz I have initiated an internal discussion on Noetic migration plans. 
Please stay tuned for updates.

**Comment by rk-yen** [comment]
Hi,

Any update on this?

**Comment by atyshka** [comment]
+1 on this, I may be able to contribute some. Once this is updated it would also be great to get buildfarm builds for noetic

**Comment by atyshka** [comment]
@raghaprasad Any updates on noetic plans?
